version: '3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    restart: always
    expose:
      - 8020
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static:/code/static/
      - media:/code/media/
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8020"

  nginx:
    build: ./nginx
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 80:80
    depends_on:
      - web