# Generated by Django 3.1.1 on 2020-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.IntegerField(default=0),
        ),
    ]
