# Generated by Django 3.1.1 on 2020-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
