# Generated by Django 3.1.1 on 2020-09-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20200907_1238"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
