# Generated by Django 3.1.1 on 2020-09-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_auto_20200913_1145"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
